services:
  ovms:
    image: openvino/model_server:latest-gpu
    volumes:
      - ./models:/models
      - /usr/lib/wsl:/usr/lib/wsl
    devices:
      - /dev/dxg:/dev/dxg
    ports:
      - "8000:8000"
    command: --config_path /models/config.json --rest_port 8000
